### ISSUE TITLE
Fix support for special characters for database Password

### ISSUE THREAD

**Issue by xkons** [webfactory/slimdump#18]
Im doctrine/dbal Projekt gibt es schon einen pull-request zu diesem Problem:
https://github.com/doctrine/dbal/pull/2504

Ein Beispiel:
_bin/slimdump mysql://user:U/js!jds*js(epupi@host:port/datebase live2dev.xml_

gibt zurück: _-bash: !jds*js: event not found_

Das würde allein schon wegen Bash nicht funktionieren, wenn wir die Sonderzeichen also escapen:
_bin/slimdump mysql://user:U\/js!jds*js(epupi@host:port/datebase live2dev.xml_

bekommen wir: _Database error: Malformed parameter "url"._

da die URL nicht enkodiert ist. Dieses Problem ist jedoch phlough spezifisch.

**HIER DER SLIMDUMP BETREFFENDE TEIL:**
angenommen wir bekommen von phlough eine enkodierte url zurück, dann würde unser slimdump Befehl folgendermaßen aussehen:
_bin/slimdump mysql://user:U%2Fjs%21jds%2Ajs%28epupi@host:port/datebase live2dev.xml_

Dann bekommen wir
_[PDOException]
  SQLSTATE[28000] [1045] Access denied for user '...'@'localhost' (using password: YES)_

Das kommt daher, dass, wie im oben genannten github pull request auf doctrine/dbal, die url nicht dekodiert wird.
Es bleibt also abzuwarten, dass dieser pull request gemerged wird.

**Comment by Matthimatiker** [comment]
@xkons Can you provide an example?

**Comment by mpdude** [comment]
Please try again and use single quotes ('') around arguments to make sure your shell does not try to expand them.

**Comment by mpdude** [comment]
If you want to learn more about why your initial command failed, read about shell history expansion: http://unix.stackexchange.com/questions/3747/understanding-the-exclamation-mark-in-bash#comment445010_3749

**Comment by mpdude** [comment]
@xkons do you consider this still an issue?

**Comment by dritter** [comment]
A shot in the dark: Would't it be sufficient to wrap the mysql-URI in single quotes to prevent bash from interpreting it as bash code? No need for url encoding..
