### ISSUE TITLE
Support for triggers

### ISSUE THREAD

**Issue by mpdude** [webfactory/slimdump#26]
It would be nice if the dump could include `CREATE TRIGGER ...` statements as well. Maybe it could also make sense to define on a per-table level whether to include triggers or not.

IMO we should not include the `... DEFINER=...` section in the dump as it makes it difficult to re-import it into another database or as another user – something `/mysql(d|p)ump/` cannot easily handle,
 at least not before 5.7 (see http://stackoverflow.com/questions/9446783/remove-definer-clause-from-mysql-dumps).

**Comment by mpdude** [comment]
Oh, maybe do the same for `CREATE VIEW ...` statements? /ping @MalteWunsch

**Comment by sebastiankugler** [comment]
I remember having that problem (definer) with views actually. I guess we're not using views at the moment though, so that's not urgent. Would make sense though, so we should go for it if it can be done easily
