### ISSUE TITLE
"masked" does not work well for columns with unique keys

### ISSUE THREAD

**Issue by mpdude** [webfactory/slimdump#29]
Assume, for example, you have an `email` column in some table and would like to dump it `masked`.

To make sure email addresses can be used as login names, a `unique` index is defined on the `email` column.

You can probably create the dump, but the import will fail because the masked addresses are no longer unique (given that your userbase is not trivially small).

One way to fix this is to make part of the "mask" a unique string, or append some unique id to it. 

Implementation bonus points: Find a reproducible way for this, so that you can still make sensible `diff`s  between two dumps without too much noise.

**Comment by janopae** [comment]
"replace" now supports modifiers for the Faker, so replace could now create unique fake e-mail addresses for this purpose. This should solve the main issue of this topic, so the issue could now be closed.
