### ISSUE TITLE
Support symfony/console 3.x

### ISSUE THREAD

**Issue by Mondane** [webfactory/slimdump#32]
Is it possible to support symfony/console version 3.x to make use of the new features in it? Currently I had to downgrade the console just for slimdump.

**Comment by mpdude** [comment]
Indeed supporting 3.x would be a good thing. As we're currently very busy – do you think you could create a PR for that? 

Are there any breaking changes between 2.x and 3.x?

**Comment by MalteWunsch** [comment]
@Mondane Please find the issue solved in slimdump 1.7.0.
