### ISSUE TITLE
remove global connect function

### ISSUE THREAD

**Issue by dknx01** [webfactory/slimdump#37]
In the util.php file is a global function "connect". This should be moved to a namespace and not be global.

This leads to the problem with redeclaring the method if other libraries also used global functions (unfortunately).

> Cannot redeclare connect() (previously declared in ....

There are also other global functions inside this class and should be also move to a namespace.

**Comment by mpdude** [comment]
Oh yes - definitely remainders of ancient ages before PHP had namespaces 😶

**Comment by mpdude** [comment]
Maybe @janopae can create a PR for this?
