### ISSUE TITLE
Add a mechanism to conditionally select rows to dump

### ISSUE THREAD

**Issue by dritter** [webfactory/slimdump#4]
In some cases you want to dump only rows that match a specific criteria. In plain SQL this is the WHERE-clause.

Could be like:
```xml
<?xml version="1.0" ?>
<slimdump>
    <table name="user" dump="full" condition="first_name LIKE 'foo%' />
</slimdump>
```
So only users with first name starts with `foo` will be dumped.

**Comment by mpdude** [comment]
Great job!
