### ISSUE TITLE
simplexml_load_string error

### ISSUE THREAD

**Issue by djeswani1** [webfactory/slimdump#42]
I am gettign this error while running the command 
slimdump mysql://root:root@localhost:3306/DB1 dump.xml > updateddump.sql

Error trace
PHP Fatal error:  Uncaught Error: Call to undefined function Webfactory\Slimdump\Config\simplexml_load_string() in /home/developer/.config/composer/vendor/webfactory/slimdump/src/Webfactory/Slimdump/Config/ConfigBuilder.php:29
Stack trace:
#0 /home/developer/.config/composer/vendor/webfactory/slimdump/src/Webfactory/Slimdump/Config/ConfigBuilder.php(68): Webfactory\Slimdump\Config\ConfigBuilder::createFromXmlString('<?xml version="...')
#1 /home/developer/.config/composer/vendor/webfactory/slimdump/src/Webfactory/Slimdump/Config/ConfigBuilder.php(51): Webfactory\Slimdump\Config\ConfigBuilder::createConfigurationFromConsecutiveXmlStrings(Array)
#2 /home/developer/.config/composer/vendor/webfactory/slimdump/src/Webfactory/Slimdump/SlimdumpCommand.php(52): Webfactory\Slimdump\Config\ConfigBuilder::createConfigurationFromConsecutiveFiles(Array)
#3 /home/developer/.config/composer/vendor/symfony/console/Command/Command.php(252): Webfactory\Slimdump\SlimdumpCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /home/developer/.config/composer/vendor/webfactory/slimdump/src/Webfactory/Slimdump/Config/ConfigBuilder.php on line 29

Any idea what could be the issue

**Comment by mpdude** [comment]
My guess is you don't have the `simplexml` extension installed or activated. For example, on newer Ubuntu releases this is contained in a separate package like `php7.1-xml`.

If you like, you could open a pull request to add a platform package requirement in `composer.json`.
