### ISSUE TITLE
please add a faker example

### ISSUE THREAD

**Issue by kaystrobach** [webfactory/slimdump#45]
Your examples just show the ultra basic usage, it would be genius to have more advanced ones esp. with the user of faker.

**Comment by mpdude** [comment]
In fact, I haven’t used it myself yet, but maybe @franziskahahn can help?

**Comment by MalteWunsch** [comment]
Do you have anything specific in mind? For me, the last example + some company formatters was sufficient so far, so I'm not sure in which direction to go to.

**Comment by kaystrobach** [comment]
Maybe how to decide which faker to use. If you have an e-mail column etc.

**Comment by franziskahahn** [comment]
We can of course add more information to the readme ( https://github.com/webfactory/slimdump/blob/master/README.md ). There is already a short eMail example. 

But in general I would like to prevent duplication stuff which is already in the faker documentation ( https://github.com/fzaninotto/Faker/blob/master/readme.md#formatters ). This would in long term lead to inconsistency in slimdump documentation.

**Comment by kaystrobach** [comment]
Does faker auto detect the content structure?

<column name="email" dump="masked" />

**Comment by franziskahahn** [comment]
No, you have to define which formatter you want to use for which of your fields :) 

It might be helpful for us to help you if you explain us a bit more in detail what you are trying to do and at which position in this workflow you stuck.

**Comment by franziskahahn** [comment]
PS: Falls es dir auf deutsch leichter fällt, frag‘ auf deutsch :D

**Comment by kaystrobach** [comment]
Gotcha, for whatever reason I have not recognized the following lines:

<column name="email" dump="replace" replacement="FAKER_unique->safeEmail" />

I was looking for an example like that - nothing more.
