### ISSUE TITLE
Provide PostSQL

### ISSUE THREAD

**Issue by kaystrobach** [webfactory/slimdump#47]
For some scenarios it would be genius to have some kind of static post SQL Option in slimdump.

For example we have some cases where the users has an contact mail and another mail address for the account. in 99% of the reallive cases these 2 are in sync. To have that ensured it would make sense to run an update query based on one of the tables afterwards.

Second scenario: export accounts, fake usernames, but set one to a known one with a known password after import to ensure that the devs have a consistent sql dump.

Our workaround would be to have these queries stored in a second sql file, which is then merged on export. Having it in the slimdump file would make it more convinient.

**Comment by mpdude** [comment]
Thanks for your suggestion!

Regarding the first use case, that seems a bit out of scope for what `slimdump` currently is about... I mean, if the data is possibly inconsistent in your production DB, isn't a "post SQL" script the wrong place to fix it?

Regarding the admin/test account, here's what we're using in such cases. This dumps only the `admin` user and changes the password (crypted) to `test`:

```xml
<table name="my_user_table" dump="full" condition="login = 'admin'" keep-auto-increment="false" >
    <!-- Passwort: test -->
    <column name="password" dump="replace" replacement="$2y$10$MbVaucH5eciZrHdos3nKpei21bvabE4GZ0UOiEXqRGyVXtKMy93sq"/>
</table>
```
If you need all users, you could skipt the `condition` attribute.

Does that help?

**Comment by MalteWunsch** [comment]
For me, this seems to be out of scope, too. What we do is just calling mysqldump to generate a dump file. We do not import the dump in a database, so we do not even have a mysql server capable of executing the SQL statements (and then dumping the result again, overwriting the first inconsistent dump?).

But I ran into this problem, too, and ended up with a similar workaround. What I wanted to have was a shell script that

- creates the dump file if does not exist yet
- append SQL statements to the dump file to create a fixed admin user account (there was no admin user present in the live data, so just replacing personal data and password and overtaking an existing account would not have worked)
- imports the dump in my development database

That took me some lines of bash code, but the functionality seemed to justify them, and with slimdump being only one small cog in the machine, that didn't feel like a workaround to me.

**Comment by kaystrobach** [comment]
mhmm ok - then i will go this way as well, or we simply have 2 shell scripts -.-

thank you for your time
