### ISSUE TITLE
keep-auto-increment="false" removes not only the auto_increment value, but also the auto_increment property

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/slimdump#55]
I've used `keep-auto-increment="false"` in schema dumps to keep things clean. My false expectation was that `keep-auto-increment="false"` would only remove the AUTO_INCREMENT=x part in the table generation DDL where the offset is set. But it also removes the AUTO_INCREMENT property off the column.

Hence, if the AUTO_INCREMENT column has a unique constraint (which it has to have at least in MySQL 5.x), INSERTs on tables based on such schema dumps fail if they don't specify a value for the AUTO_INCREMENT column. This seems to be a subtle source of errors.

Is this the intended behaviour? In this case, I'd like to see a warning in the documentation; otherwhise I suggest to change the behaviour / add a new option.

**Comment by sebastiankugler** [comment]
I cannot imagine this is intended behaviour. On the contrary, I now begin to understand how several auto_increment properties may have vanished in the recent past.

The code responsible for handling the keepAutoIncrement is here:
https://github.com/webfactory/slimdump/blob/master/src/Webfactory/Slimdump/Database/Dumper.php#L61

At first glance it looks as if it only removed the value, as to my understanding the AUTO_INCREMENT property is part of the column definition, whereas AUTO_INCREMENT=123 is part of the table options (https://dev.mysql.com/doc/refman/8.0/en/create-table.html)

This is what the export in PhpMyAdmin generates:
ALTER TABLE `XXX`
  MODIFY `id` smallint(5) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=856;
COMMIT;

**Comment by sebastiankugler** [comment]
I could not reproduce this problem using a local database with this simple config:

`<?xml version="1.0" ?>

<slimdump>
    <table name="youthpass_project" dump="schema" keep-auto-increment="false" />
</slimdump>`

The AUTO_INCREMENT property was dumped and only the value stripped.

**Comment by mpdude** [comment]
@MalteWunsch I also checked this and could not reproduce.

Are you sure the `AUTO_INCREMENT` attribute was not missing in your source database in the first place?

**Comment by MalteWunsch** [comment]
Nah, my bad. I've misread my dump.

Maybe I'll stumble upon our disappearing AUTO_INCREMENTs in my next similar project, I've added double-checking that onto my list.
