### ISSUE TITLE
DSN format

### ISSUE THREAD

**Issue by mpdude** [webfactory/slimdump#6]
We have a somewhat limited idea of what a DSN has to look like (https://github.com/webfactory/slimdump/blob/master/php/util.php#L20).

What would be better/more flexible/open ways to specify DB connection params?

**Comment by mpdude** [comment]
Once #3 is merged, we simply pass the DSN to DBAL, so we could refer to http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url for an explanation.

Still, we require the use of UTF-8 for the time being.

**Comment by dritter** [comment]
Done.
